version: '3.8'

services:
  # Ollama Service for Local LLM
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - coffee-network
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Main Coffee Caption Generator App
  coffee-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-phi3:mini}
      - DB_HOST=coffee-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-reddit_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres123}
      - OAUTH_SERVICE_URL=http://oauth-service:8001
      - OAUTH_SERVICE_API_KEY=${OAUTH_SERVICE_API_KEY:-dev-service-key-change-in-production}
    volumes:
      - .:/app
    depends_on:
      coffee-db:
        condition: service_healthy
      oauth-service:
        condition: service_started
      ollama:
        condition: service_healthy
    networks:
      - coffee-network

  # OAuth Service
  oauth-service:
    build:
      context: ./social-oauth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      # Application
      - APP_NAME=Social OAuth Service
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8001
      
      # Database
      - DB_HOST=oauth-db
      - DB_PORT=5432
      - DB_NAME=${OAUTH_DB_NAME:-oauth_db}
      - DB_USER=${OAUTH_DB_USER:-postgres}
      - DB_PASSWORD=${OAUTH_DB_PASSWORD:-oauth_pass}
      
      # Security
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SERVICE_API_KEY=${OAUTH_SERVICE_API_KEY:-dev-service-key-change-in-production}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      
      # OAuth Credentials
      - INSTAGRAM_CLIENT_ID=${INSTAGRAM_CLIENT_ID}
      - INSTAGRAM_CLIENT_SECRET=${INSTAGRAM_CLIENT_SECRET}
      - INSTAGRAM_REDIRECT_URI=${INSTAGRAM_REDIRECT_URI:-http://localhost:8001/api/v1/oauth/instagram/callback}
      
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      - FACEBOOK_REDIRECT_URI=${FACEBOOK_REDIRECT_URI:-http://localhost:8001/api/v1/oauth/facebook/callback}
      
      # Base callback URL
      - BASE_CALLBACK_URL=http://localhost:8001
    volumes:
      - ./social-oauth-service:/app
    depends_on:
      oauth-db:
        condition: service_healthy
    networks:
      - coffee-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PostgreSQL for Main App
  coffee-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=reddit_db
    volumes:
      - coffee-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL for OAuth Service
  oauth-db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=oauth_pass
      - POSTGRES_DB=oauth_db
    volumes:
      - oauth-db-data:/var/lib/postgresql/data
      - ./social-oauth-service/migrations/init_oauth_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - coffee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  coffee-network:
    driver: bridge

volumes:
  coffee-db-data:
  oauth-db-data:
  ollama-data:
